# Generated by Django 4.2.6 on 2023-11-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('routeid', models.AutoField(db_column='RouteId', primary_key=True, serialize=False)),
                ('visit', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Visit', max_length=7)),
                ('journey', models.IntegerField(db_column='Journey')),
                ('routestarteddt', models.DateTimeField(db_column='RouteStartedDT')),
                ('waypointdt', models.DateTimeField(db_column='WaypointDT')),
                ('dockeddt', models.DateTimeField(blank=True, db_column='DockedDT', null=True)),
            ],
            options={
                'db_table': 'Route',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Routecategory',
            fields=[
                ('routecategoryid', models.AutoField(db_column='RouteCategoryId', primary_key=True, serialize=False)),
                ('routecategoryname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='RouteCategoryName', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'RouteCategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('shipid', models.AutoField(db_column='ShipId', primary_key=True, serialize=False)),
                ('shipname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ShipName', max_length=100)),
                ('imo', models.IntegerField(db_column='IMO')),
                ('max_length', models.DecimalField(db_column='Max_Length', decimal_places=2, max_digits=8)),
                ('max_width', models.DecimalField(db_column='Max_Width', decimal_places=2, max_digits=8)),
                ('max_draft', models.DecimalField(db_column='Max_Draft', decimal_places=2, max_digits=8)),
                ('operationaldraft', models.DecimalField(blank=True, db_column='OperationalDraft', decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'Ship',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('waypointid', models.AutoField(db_column='WaypointId', primary_key=True, serialize=False)),
                ('waypointname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='WaypointName', max_length=10, unique=True)),
                ('waypointdescription', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='WaypointDescription', null=True)),
                ('waypointlongitude', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='WaypointLongitude', null=True)),
                ('waypointlatitude', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='WaypointLatitude', null=True)),
            ],
            options={
                'db_table': 'Waypoint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zoneto',
            fields=[
                ('zonetoid', models.AutoField(db_column='ZoneToId', primary_key=True, serialize=False)),
                ('zonetoname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ZoneToName', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'ZoneTo',
                'managed': False,
            },
        ),
    ]
