# Generated by Django 4.2.6 on 2024-01-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeaYou_Models', '0002_accesstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashed_weather_data', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CashedWeatherData', null=True)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
