# Generated by Django 4.2.6 on 2024-01-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeaYou_Models', '0003_weathercache'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETACache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name', default='port', max_length=50)),
                ('cashed_eta_data', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CashedETAData', null=True)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
